import CHI1 from '../src/assets/CHI1.png'
import CHI2 from '../src/assets/CHI2.png'
import GA1 from '../src/assets/GA1.png'
import LA1 from '../src/assets/LA1.png'
import LA2 from '../src/assets/LA2.png'
import MA1 from '../src/assets/MA1.png'
import MA2 from '../src/assets/MA2.png'
import MO1 from '../src/assets/MO1.png'
import NC1 from '../src/assets/NC1.png'
import NC2 from '../src/assets/NC2.png'
import NY1 from '../src/assets/NY1.png'
import NY2 from '../src/assets/NY2.png'
import NYC1 from '../src/assets/NYC1.png'
import NYC2 from '../src/assets/NYC2.png'
import OH1 from '../src/assets/OH1.png'
import PA1 from '../src/assets/PA1.png'
import PA2 from '../src/assets/PA2.png'
import PHX1 from '../src/assets/PHX1.png'
import TX1 from '../src/assets/TX1.png'
import VA1 from '../src/assets/VA1.png'
import IN1 from '../src/assets/IN1.png'


export const concerts = [
  {
    id: 0,
    venue: 'Inglewood, CA',
    date: '05/19/2023',
    poster: `${LA1}`,
    set1: [
      'Shakedown Street',
      'Cold Rain & Snow',
      'Mississippi 1/2 Step',
      'They Love Each Other',
      'St.Stephen',
      'The Eleven',
      'Deal',
    ],
    set2: [
      'Sugaree',
      'New Speedway Boogie',
      'Eyes of the World',
      'Estimated Prophet',
      'Drums',
      'Space',
      'The Wheel',
      'Wharf Rat',
      'Sugar Magnolia',
    ],
    encore: ['Black Muddy River'],
    region: 'West',
  },
  {
    id: 1,
    venue: 'Inglewood, CA',
    date: '05/20/2023',
    poster: `${LA2}`,
    set1: [
      'Bertha',
      'Good Lovin',
      'Brown-eyed Women',
      'Jack Straw',
      'High Time',
      'Mr.Charlie',
      'Bird Song',
      'Dont Ease Me In',
    ],
    set2: [
      'Althea',
      'The Other One',
      'Terrapin Station',
      'The Other One',
      'Drums',
      'Space',
      'Stella Blue',
      'Help on the Way',
      'Slipknot!',
      'Franklins Tower',
    ],
    encore: ['Brokedown Palace'],
    region: 'West',
  },
  {
    id: 2,
    venue: 'Phoenix, AZ',
    date: '05/23/2023',
    poster: `${PHX1}`,
    set1: [
      'Feel Like a Stranger',
      'Alabama Getaway',
      'Ramble on Rose',
      'Dear Mr.Fantasy',
      'Hey Jude',
      'Dark Star',
      'Cumberland Blues',
      'Casey Jones',
    ],
    set2: [
      'Here Comes Sunshine',
      'Scarlet Begonias',
      'Viola Lee Blues',
      'Dark Star',
      'Spanish Jam',
      'Fire on the Mountain',
      'Drums',
      'Space',
      'I Need a Miracle',
      'Death Dont Have No Mercy',
      'U.S. Blues',
    ],
    encore: ['Ripple'],
    region: 'West',
  },
  {
    id: 3,
    venue: 'Dallas, TX',
    date: '05/26/2023',
    poster: `${TX1}`,
    set1: [
      'Let the Good Times Roll',
      'Hell in a Bucket',
      'Big Railroad Blues',
      'Lost Sailor',
      'Saint of Circumstance',
      'Ship of Fools',
      'Brown-eyed Women',
      'The Music Never Stopped',
    ],
    set2: [
      'Jack Straw',
      'Truckin',
      'Hes Gone',
      'Playing in the Band',
      'Uncle Johns Band',
      'Drums',
      'Space',
      'All Along the Watchtower',
      'Playing in the Band Reprise',
      'Standing on the Moon',
      'Not Fade Away',
    ],
    encore: ['Touch of Grey'],
    region: 'South',
  },
  {
    id: 4,
    venue: 'Atlanta, GA',
    date: '05/28/2023',
    poster: `${GA1}`,
    set1: [
      'Cassidy',
      'Deal',
      'Samson & Delilah',
      'Friend of the Devil',
      'It Hurts Me Too',
      'Tennessee Jed',
      'If I Had the World to Give',
      'GDTRFB',
    ],
    set2: [
      'Althea',
      'Estimated Prophet',
      'China Cat Sunflower',
      'I Know You Rider',
      'Eyes of the World',
      'Drums',
      'Space',
      'Terrapin Station',
      'Morning Dew',
    ],
    encore: ['None'],
    region: 'South',
  },
  {
    id: 5,
    venue: 'Charlotte, NC',
    date: '05/30/2023',
    poster: `${NC1}`,
    set1: [
      'Shakedown Street',
      'Cold Rain & Snow',
      'Loser',
      'Dire Wolf',
      'Loose Lucy',
      'The Wheel',
      'Bertha',
      'Let it Grow',
    ],
    set2: [
      'Help on the Way',
      'Slipknot!',
      'Franklins Tower',
      'Fire on the Mountain',
      'The Other One',
      'Drums',
      'Space',
      'The Other One',
      'Black Peter',
      'Sugar Magnolia',
    ],
    encore: ['U.S. Blues'],
    region: 'South',
  },
  {
    id: 6,
    venue: 'Raleigh, NC',
    date: '06/01/2023',
    poster: `${NC2}`,
    set1: [
      'New Speedway Boogie',
      'They Love Each Other',
      'Mama Tried',
      'Easy Wind',
      'Ramble on Rose',
      'Dear Mr.Fantasy',
      'Hey Jude',
      'Bird Song',
    ],
    set2: [
      'Sugaree',
      'St.Stephen',
      'The Eleven',
      'Iko, Iko',
      'Drums',
      'Space',
      'I Need a Miracle',
      'Wharf Rat',
      'Casey Jones',
    ],
    encore: ['Black Muddy River'],
    region: 'South',
  },
  {
    id: 7,
    venue: 'Bristow, VA',
    date: '06/03/2023',
    poster: `${VA1}`,
    set1: [
      'Here Comes Sunshine',
      'Mississippi 1/2 Step',
      'Mr.Charlie',
      'Hes Gone',
      'Brown-eyed Women',
      'Dear Prudence',
      'Turn On Your Love Light',
    ],
    set2: [
      'Deal',
      'Scarlet Begonias',
      'Playing in the Band',
      'Cumberland Blues',
      'Uncle Johns Band',
      'Drums',
      'Space',
      'Milestones',
      'Days Between',
      'Throwing Stones',
      'One More Saturday Night',
    ],
    encore: ['Ripple'],
    region: 'South',
  },
  {
    id: 8,
    venue: 'Burgettstown, PA',
    date: '06/05/2023',
    poster: `${PA1}`,
    set1: [
      'Hell in a Bucket',
      'Alabama Getaway',
      'Jack Straw',
      'Big Boss Man',
      'Peggy-O',
      'Bertha',
      'Cassidy',
      'Dont Ease Me In',
    ],
    set2: [
      'Viola Lee Blues',
      'Truckin',
      'China Doll',
      'China Cat Sunflower',
      'I Know You Rider',
      'Drums',
      'Space',
      'Althea',
      'Standing on the Moon',
      'Not Fade Away',
    ],
    encore: ['The Weight'],
    region: 'Northeast',
  },
  {
    id: 9,
    venue: 'Maryland Heights, MO',
    date: '06/07/2023',
    poster: `${MO1}`,
    set1: [
      'Let the Good Times Roll',
      'Big River',
      'Friend of the Devil',
      'They Love Each Other',
      'Black-throated Wind',
      'Big Railroad Blues',
      'Dark Star',
      'Johnny B. Goode',
    ],
    set2: [
      'Eyes of the World',
      'Dark Star',
      'Fire on the Mountain',
      'Shakedown Street',
      'Drums',
      'Space',
      'The Eleven',
      'Death Dont Have No Mercy',
      'GDTRFB',
    ],
    encore: ['Knockin On Heavens Door'],
    region: 'Midwest',
  },
  {
    id: 10,
    venue: 'Chicago, IL',
    date: '06/09/2023',
    poster: `${CHI1}`,
    set1: [
      'Playing in the Band',
      'Deal',
      'Tennessee Jed',
      'It Hurts Me Too',
      'Ramble on Rose',
      'Brown-eyed Women',
      'Crazy Fingers',
      'Dancing in the Street',
    ],
    set2: [
      'Sugaree',
      'Estimated Prophet',
      'The Other One',
      'Terrapin Station',
      'Drums',
      'Space',
      'Stella Blue',
      'Sugar Magnolia',
      'Scarlet Begonias',
      'Sunshine Daydream',
    ],
    encore: ['U.S. Blues'],
    region: 'Midwest',
  },
  {
    id: 11,
    venue: 'Chicago, IL',
    date: '06/10/2023',
    poster: `${CHI2}`,
    set1: [
      'Truckin',
      'Smokestack Lightning',
      'Althea',
      'Mississippi 1/2 Step',
      'High Time',
      'All Along the Watchtower',
      'Bertha',
      'Good Lovin',
    ],
    set2: [
      'Help on the Way',
      'Slipknot!',
      'Franklins Tower',
      'St.Stephen',
      'Drums',
      'Space',
      'Uncle Johns Band',
      'Cumberland Blues',
      'The Other One',
      'Morning Dew',
    ],
    encore: [
      'Brokedown Palace',
      'Playing in the Band',
      'One More Saturday Night',
    ],
    region: 'Midwest',
  },
  {
    id: 12,
    venue: 'Cincinnati, OH',
    date: '06/13/2023',
    poster: `${OH1}`,
    set1: [
      'The Music Never Stopped',
      'Next Time You See Me',
      'Me and my Uncle',
      'Row Jimmy',
      'Dear Mr.Fantasy',
      'Hey Jude',
      'Cassidy',
      'Iko, Iko',
    ],
    set2: [
      'Here Comes Sunshine',
      'Viola Lee Blues',
      'Looks Like Rain',
      'China Cat Sunflower',
      'I Know You Rider',
      'Drums',
      'Space',
      'The Wheel',
      'Wharf Rat',
      'Casey Jones',
    ],
    encore: ['Touch of Grey'],
    region: 'Midwest',
  },
  {
    id: 13,
    venue: 'Philadelphia, PA',
    date: '06/15/2023',
    poster: `${PA2}`,
    set1: [
      'Women are Smarter',
      'Shakedown Street',
      'Cold Rain & Snow',
      'Jack Straw',
      'Brown-eyed Women',
      'Dark Star',
      'El Paso',
      'Dont Ease Me In',
    ],
    set2: [
      'Fire on the Mountain',
      'New Speedway Boogie',
      'Estimated Prophet',
      'Eyes of the World',
      'Drums',
      'Space',
      'Dark Star',
      'Cumberland Blues',
      'Standing on the Moon',
      'Not Fade Away',
    ],
    encore: ['Ripple'],
    region: 'Northeast',
  },
  {
    id: 14,
    venue: 'Saratoga, NY',
    date: '06/17/2023',
    poster: `${NY1}`,
    set1: [
      'Let the Good Times Roll',
      'Scarlet Begonias',
      'Deal',
      'Black-throated Wind',
      'Dire Wolf',
      'Bird Song',
      'GDTRFB',
    ],
    set2: [
      'They Love Each Other',
      'Terrapin Station',
      'Hes Gone',
      'The Other One',
      'Drums',
      'Space',
      'The Other One',
      'Days Between',
      'Turn On Your Love Light',
    ],
    encore: ['One More Saturday Night'],
    region: 'Northeast',
  },
  {
    id: 15,
    venue: 'Saratoga, NY',
    date: '06/18/2023',
    poster: `${NY2}`,
    set1: [
      'Hell in a Bucket',
      'Sugaree',
      'Mississippi 1/2 Step',
      'Mr.Charlie',
      'Friend of the Devil',
      'Lost Sailor',
      'Saint of Circumstance',
      'Big Railroad Blues',
    ],
    set2: [
      'Samson & Delilah',
      'Playing in the Band',
      'Help on the Way',
      'Slipknot!',
      'Franklins Tower',
      'Drums',
      'Space',
      'Death Dont Have No Mercy',
      'Throwing Stones',
      'Sugar Magnolia',
    ],
    encore: ['Werewolves of London', 'Playing in the Band Reprise'],
    region: 'Northeast',
  },
  {
    id: 16,
    venue: 'New York, NY',
    date: '06/21/2023',
    poster: `${NYC1}`,
    set1: [
      'Shakedown Street',
      'Bertha',
      'Ramble on Rose',
      'It Hurts Me Too',
      'Dancing in the Street',
      'Althea',
      'Let it Grow',
    ],
    set2: [
      'China Cat Sunflower',
      'I Know You Rider',
      'St.Stephen',
      'Uncle Johns Band',
      'Drums',
      'Space',
      'The Eleven',
      'Stella Blue',
      'U.S. Blues',
    ],
    encore: ['Black Muddy River'],
    region: 'Northeast',
  },
  {
    id: 17,
    venue: 'New York, NY',
    date: '06/22/2023',
    poster: `${NYC2}`,
    set1: [
      'Feel Like a Stranger',
      'Franklins Tower',
      'Mama Tried',
      'Alabama Getaway',
      'Dear Mr.Fantasy',
      'Hey Jude',
      'Truckin',
      'Deal',
    ],
    set2: [
      'Scarlet Begonias',
      'Fire on the Mountain',
      'Estimated Prophet',
      'Eyes of the World',
      'Drums',
      'Space',
      'All Blues',
      'Cumberland Blues',
      'All Along the Watchtower',
      'Morning Dew',
    ],
    encore: ['Brokedown Palace'],
    region: 'Northeast',
  },
  {
    id: 18,
    venue: 'Boston, MA',
    date: '06/24/2023',
    poster: `${MA1}`,
    set1: [
      'Cassidy',
      'Brown-eyed Women',
      'I Need a Miracle',
      'Here Comes Sunshine',
      'Tennessee Jed',
      'China Doll',
      'Viola Lee Blues',
      'The Music Never Stopped',
    ],
    set2: [
      'New Speedway Boogie',
      'Dark Star',
      'The Other One',
      'Terrapin Station',
      'Drums',
      'Space',
      'Dark Star On The Big River Jam',
      'The Other One Jam',
      'Black Peter',
      'Casey Jones',
      'One More Saturday Night',
    ],
    encore: ['None'],
    region: 'Northeast',
  },
  {
    id: 19,
    venue: 'Boston, MA',
    date: '06/25/2023',
    poster: `${MA2}`,
    set1: [
      'Samson & Delilah',
      'Cold Rain & Snow',
      'Jack Straw',
      'Althea',
      'Comes a Time',
      'Mr.Charlie',
      'Hes Gone',
      'GDTRFB',
    ],
    set2: [
      'They Love Each Other',
      'Playing in the Band',
      'Help on the Way',
      'Slipknot!',
      'Fire on the Mountain',
      'Drums',
      'Space',
      'Playing in the Band Reprise',
      'The Other One',
      'Standing on the Moon',
      'Not Fade Away',
    ],
    encore: ['The Weight', 'Ripple'],
    region: 'Northeast',
  },
  {
    id: 20,
    venue: 'Noblesville, IN',
    date: '06/27/23',
    poster: `${IN1}`,
    set1: [
      'Bertha', 'Good Lovin', 'It Must Have Been the Roses', 'Big River', 'Dark Star On The Big River Jam', 'Next Time You See Me', 'Mississippi 1/2 Step', 'Bird Song', 'Dont Ease Me In'
    ],
    set2: [
      'Iko, Iko', 'Sugaree', 'China Cat Sunflower', 'I Know You Rider', 'Uncle Johns Band', 'Drums', 'Space','Hell in a Bucket', 'Wharf Rat', 'Turn On Your Love Light'
    ],
    encore: ['Touch of Grey'],
    region: 'Midwest',
  },
  // {id: 15, venue: 'Noblesville, IN'},
  // {id: 16, venue: 'Boulder, CO'},
  // {id: 17, venue: 'George, WA'},
  // {id: 18, venue: 'San Francisco, CA'}
]

export const cities = [
  'Inglewood, CA',
  'Phoenix, AZ',
  'Dallas, TX',
  'Atlanta, GA',
  'Charlotte, NC',
  'Raleigh, NC',
  'Bristow, VA',
  'Burgettstown, PA',
  'Maryland Heights, MO',
  'Chicago, IL',
  'Cincinnati, OH',
  'Philadelphia, PA',
  'Saratoga, NY',
  'New York, NY',
  'Boston, MA',
]
