export const locations = [
    {id: 0, venue: 'Inglewood, CA'},
    {id: 1, venue: 'Phoenix, AZ'},
    {id: 2, venue: 'Dallas, TX'},
    {id: 3, venue: 'Atlanta, GA'},
    {id: 4, venue: 'Charlotte, NC'},
    {id: 5, venue: 'Raleigh, NC'},
    {id: 6, venue: 'Bristow, VA'},
    {id: 7, venue: 'Burgettstown, PA'},
    {id: 8, venue: 'Maryland Heights, MO'},
    {id: 9, venue: 'Chicago, IL'},
    {id: 10, venue: 'Cincinnati, OH'},
    {id: 11, venue: 'Philadelphia, PA'},
    {id: 12, venue: 'Saratoga, NY'},
    {id: 13, venue: 'New York, NY'},
    {id: 14, venue: 'Boston, MA'},
    {id: 15, venue: 'Noblesville, IN'},
    {id: 16, venue: 'Boulder, CO'},
    {id: 17, venue: 'George, WA'},
    {id: 18, venue: 'San Francisco, CA'}
]